version: '3.8'

services:
  web:
    container_name: travel_wallet_web
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    labels:
      - "com.microsoft.devcontainer.name=travel-wallet"

  db:
    container_name: travel_wallet_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: travel_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "6543:5432" 
volumes:
  pg_data:
